### ISSUE TITLE
Usare funzioni portabili (strtok_r vs __strtok_r)

### ISSUE THREAD

**Issue by lucaderi** [gabryon99/dummyshell#2]
--- a/src/dummyshell.c
+++ b/src/dummyshell.c
@@ -24,7 +24,7 @@ void cd_handler(char* input) {
 
     char* path = strstr(input, " ") + 1;
     char* token_state = NULL;
-    char* tokenized_path = __strtok_r(path, "\n", &token_state);
+    char* tokenized_path = strtok_r(path, "\n", &token_state);
 
     fprintf(stdout, "path: %s\n", tokenized_path);
 
@@ -163,4 +163,4 @@ bool execute_builtin(char* buffer) {
     }
 
     return false;
-}
\ No newline at end of file
+}

**Comment by gabryon99** [comment]
Ok! Adesso uso la versione `strtok_r` che e' portatile!

**Comment by gabryon99** [comment]
Fatto! https://github.com/gabryon99/dummyshell/commit/5f7fedd8c8421e0c93ae4bbd68841b3ef2d9644b
