### ISSUE TITLE
Control-d causa un loop infinito

### ISSUE THREAD

**Issue by lucaderi** [gabryon99/dummyshell#4]
deri@Lucas-iMac.local:/private/tmp/dummyshell $ 
deri@Lucas-iMac.local:/private/tmp/dummyshell $ 
deri@Lucas-iMac.local:/private/tmp/dummyshell $ 
deri@Lucas-iMac.local:/private/tmp/dummyshell $ 
deri@Lucas-iMac.local:/private/tmp/dummyshell $ 
deri@Lucas-iMac.local:/private/tmp/dummyshell $ 
deri@Lucas-iMac.local:/private/tmp/dummyshell $ 
deri@Lucas-iMac.local:/private/tmp/dummyshell $ 
deri@Lucas-iMac.local:/private/tmp/dummyshell $ 
deri@Lucas-iMac.local:/private/tmp/dummyshell $ 
deri@Lucas-iMac.local:/private/tmp/dummyshell $ 
deri@Lucas-iMac.local:/private/tmp/dummyshell $ 
deri@Lucas-iMac.local:/private/tmp/dummyshell $

**Comment by gabryon99** [comment]
Fixato! Il problema stava nella segnalazione di un EOF allo standard input inviato da Ctrl+D che non veniva ripulito: https://github.com/gabryon99/dummyshell/commit/e0d29fc27e93d100f4699a9d8f5b5181903a0d81
